POPULATION_SIZE = 10
NUMBER_OF_ITERATIONS = 20
ELITISM = POPULATION_SIZE/4 #number of individuals to copy to the next generation
TOURNAMENT = 5
PROB_CROSSOVER = 1
PROB_MUTATION = 1 # (lambda mapped : 1.0 / mapped)
MIN_INIT_DEPTH=4
MIN_DEPTH=None
MAX_INIT_DEPTH=8
MAX_DEPTH=19
RESULTS_FOLDER = "results"
PENALIZE_PERC = 0.2

TRAIN_SIZE = 5000
VALID_SPLIT = 0.1
EPOCHS = 10
BATCH = 128
