POPULATION_SIZE = 20
NUMBER_OF_ITERATIONS = 25
ELITISM = POPULATION_SIZE/4 #number of individuals to copy to the next generation
TOURNAMENT = 5
PROB_CROSSOVER = 1
PROB_MUTATION = 1 # (lambda mapped : 1.0 / mapped)
MIN_INIT_DEPTH=None
MIN_DEPTH=None
MAX_INIT_DEPTH=6
MAX_DEPTH=10
RESULTS_FOLDER = "results"
PENALIZE_PERC = 0.2

TRAIN_SIZE = 5000
TEST_SIZE = 1000
VALID_SPLIT = 0.1
EPOCHS = 10
BATCH = 128
